create database runner;
use runner;

create sequence _user_type__user_type_id_seq;

alter sequence _user_type__user_type_id_seq owner to gandalf;

create sequence _user__id_user_seq;

alter sequence _user__id_user_seq owner to gandalf;

create table m_user_type
(
    _id_user_type bigint generated by default as identity
        constraint _user_type_pk
            primary key,
    title         varchar not null,
    notes         text
);

alter table m_user_type
    owner to gandalf;

alter sequence _user_type__user_type_id_seq owned by m_user_type._id_user_type;

create table m_user
(
    id__user      bigint generated by default as identity
        constraint _user_pk
            primary key,
    user_name     varchar              not null,
    user_email    varchar              not null,
    tags          character varying[],
    notes         text,
    is_active     boolean default true not null,
    image_url     varchar,
    _id_user_type bigint
        constraint _user__user_type__id_user_type_fk
            references m_user_type,
    hours_played  integer default 0    not null
);

alter table m_user
    owner to gandalf;

alter sequence _user__id_user_seq owned by m_user.id__user;

create table game_systems
(
    id_game_systems bigserial
        constraint game_systems_pk
            primary key,
    title           varchar not null,
    notes           text,
    version         varchar,
    publisher       varchar,
    website         varchar
);

alter table game_systems
    owner to gandalf;

create table games
(
    id_games        bigserial
        constraint games_pk
            primary key,
    id_game_systems bigint
        constraint games_game_systems_id_game_systems_fk
            references game_systems,
    title           varchar              not null,
    noes            text,
    image_url       varchar,
    is_active       boolean default true not null,
    id__user        bigint               not null
        constraint games__user__id_user_fk
            references m_user
);

alter table games
    owner to gandalf;

create table game_users
(
    id_game_users bigserial
        constraint game_users_pk
            primary key,
    id_games      bigint
        constraint game_users_games_id_games_fk
            references games,
    id__user      bigint
        constraint game_users__user_id__user_fk
            references m_user
);

alter table game_users
    owner to gandalf;

create table m_card_type
(
    id_m_card_type    bigserial
        constraint m_card_type_pk
            primary key,
    title             varchar not null,
    notes             text,
    custom_properties json
);

alter table m_card_type
    owner to gandalf;

create table hands
(
    id_hands bigserial
        constraint hands_pk
            primary key,
    title    varchar not null
);

alter table hands
    owner to gandalf;

